name: Lint and Format

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Add Target Branch
      run: git branch ${GITHUB_BASE_REF} origin/${GITHUB_BASE_REF}
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: List Checked Files
      run: git diff --name-only ${GITHUB_BASE_REF} HEAD
    - name: Run Pre-Commit Checks
      run: pre-commit run --show-diff-on-failure --color=always --from-ref=${GITHUB_BASE_REF} --to-ref=HEAD
