user: |-
 The following is a math competition question. Examine and solve the question correctly.

 {problem}

 Let’s think step by step. Provide your answer in the following format: Final Answer: \boxed{{}}
