# https://github.com/NVIDIA/NeMo-Skills/blob/gnalbandyan/robustness/nemo_skills/prompt/config/generic/math.yaml

user: |-
 Solve the following math problem. Make sure to put the answer (and only answer) inside \boxed{{}}.

 {problem}
