user: |-
 {problem}

 Provide your answer in the following format: Final Answer: \boxed{{}}

 This is a multiple-choice question. The final answer is expected to be a single letter. Do not provide any further information after this. This is important. If you do not provide a final answer in this format, your answer will not be scored as accurate.
