user: |-
 The following is a science question. Examine and solve the question correctly.

 {problem}

 Reflect upon this question and let’s verify step by step. Provide your answer in the following format: Final Answer: \boxed{{}}
